# Turn on/off classification enforcement. When this flag is off, this
#  completely disables the classification engine, any documents added while
#  the classification engine is off getting the default unrestricted value
enforce: false

# When this flag is on, the classification engine will automatically create
#  groups based on the domain part of a user's email address
#  EX:
#     For user with email: test@local.host
#     The group "local.host" will be valid in the system
dynamic_groups: false

# List of Classification Levels:
#   This is a graded list; a smaller number is less restricted than a higher number
#   A user must be allowed a classification level >= to be able to view the data
levels:
  # List of alternate names for the current marking. If a user submits a file with
  #  those markings, the classification will automatically rename it to the value
  #  specified in the name
  - aliases:
      - UNRESTRICTED
      - UNCLASSIFIED
      - U

    # Stylesheet applied in the UI for the current classification level
    css:
      # Name of the color scheme used for display
      # Possible values: default, primary, secondary, success, info, warning, error
      color: default

      # Deprecated parameters (Use color instead)
      #  These were used in the old UI but are still valid in the new UI because if
      #  the new UI cannot find the color param, it will use the label param and
      #  strips "label-" part.
      banner: alert-default
      label: label-default
      text: text-muted

    # Description of the classification level
    description:
      Subject to standard copyright rules, TLP:WHITE information may be distributed
      without restriction.

    # Integer value of the Classification level (higher is more classified)
    lvl: 100

    # Long name of the classification level
    name: TLP:WHITE

    # Short name of the classification level
    short_name: TLP:W
  - aliases: []
    css:
      color: success
    description:
      Recipients may share TLP:GREEN information with peers and partner organizations
      within their sector or community, but not via publicly accessible channels.
      Information in this category can be circulated widely within a particular
      community. TLP:GREEN information may not be released outside of the community.
    lvl: 110
    name: TLP:GREEN
    short_name: TLP:G
  - aliases:
      - RESTRICTED
    css:
      color: warning
    description:
      Recipients may only share TLP:AMBER information with members of their
      own organization and with clients or customers who need to know the information
      to protect themselves or prevent further harm.
    lvl: 120
    name: TLP:AMBER
    short_name: TLP:A

# List of required tokens:
#   A user requesting access to an item must have all the
#   required tokens the item has, to gain access to it
required:
  # List of alternate names for the token
  - aliases: []

    # Description of the token
    description: Produced using a commercial tool with limited distribution

    # Long name for the token
    name: COMMERCIAL

    # Short name for the token
    short_name: CMR

    # (optional) The minimum classification level an item must have
    #  for this token to be valid. So, because this token has a value
    #  of 120, once it's selected, the classification level automatically
    #  jumps to TPL:A which was set to 120 in the previous section.
    require_lvl: 120

# List of groups:
#   A user requesting access to an item must be part of a least
#   of one the group the item is part of to gain access
groups:
  # List of aliases for the group
  - aliases:
      - ANY
    # (optional) This is a special flag that when set to true if any other groups
    #  are selected in a classification, this group will automatically be selected
    #  as well.
    auto_select: true

    # Description of the group
    description: Employees of CSE

    # Long name for the group
    name: CSE

    # Short name for the group
    short_name: CSE

    # (optional) Assuming that this group is the only group selected, this is the
    #   display name that will be used in the classification
    #   NOTE: values must be in the aliases of this group and only this group
    solitary_display_name: ANY

# List of sub-groups:
#   A user requesting access to an item must be part of a least
#   of one the sub-group the item is part of to gain access
subgroups:
  # List of aliases for the subgroups
  - aliases: []

    # Description of the sub-group
    description: Member of Incident Response team

    # Long name of the sub-group
    name: IR TEAM

    # Short name of the sub-group
    short_name: IR
  - aliases: []
    description: Member of the Canadian Centre for Cyber Security

    # (optional) This is a special flag that auto select the corresponding
    #   group when this sub-group is selected
    require_group: CSE

    name: CCCS
    short_name: CCCS

    # (optional) This is a special flag that makes sure that none other than
    #   the corresponding group is selected when this sub-group is selected
    limited_to_group: CSE

# Default restricted classification
restricted: TLP:A//CMR

# Default unrestricted classification:
#   When no classification is provided or the classification engine is
#   disabled, this is the classification value each item will get
unrestricted: TLP:W
