services:
  nginx:
    image: ${REGISTRY}cccs/nginx-ssl-frontend
    ports:
      - '443:443'
    environment:
      - DOLLAR=$$
      - UI_HOST=ui
      - SOCKET_HOST=socketio
      - FRONTEND_HOST=frontend
      - FQDN=${DOMAIN}
      - MAX_BODY_SIZE=100M
    volumes:
      - ${COMPOSE_ROOT}/../config/nginx.crt:/etc/ssl/nginx.crt:ro
      - ${COMPOSE_ROOT}/../config/nginx.key:/etc/ssl/nginx.key:ro
    networks:
      - core
      - external
    restart: on-failure
