core:
  alerter:
    delay: 0
  metrics:
    apm_server:
      server_url: null
    elasticsearch:
      hosts: []
    redis:
      host: redis
      port: 6379
  scaler:
    cpu_overallocation: 8
    service_defaults:
      backlog: 10
      shrink: 20
      min_instances: 1
      environment:
        - name: SERVICE_API_KEY
          value: ${SERVICE_API_KEY}
  redis:
    nonpersistent:
      host: redis
      port: 6379
    persistent:
      host: redis
      port: 6379

datastore:
  hosts: ["http://elastic:${ELASTIC_PASSWORD}@elasticsearch:9200"]

filestore:
  cache: ["s3://al_storage_key:${FILESTORE_PASSWORD}@minio:9000?s3_bucket=al-cache&use_ssl=False"]
  storage: ["s3://al_storage_key:${FILESTORE_PASSWORD}@minio:9000?s3_bucket=al-storage&use_ssl=False"]

logging:
  log_level: WARNING
  log_as_json: false
  log_to_console: true
  log_to_file: false
  log_to_syslog: false

services:
  image_variables:
    REGISTRY: ${REGISTRY}

submission:
  file_sources:
    - name: MalwareBazaar
      data: query=get_file&sha256_hash={SHA256}
      failure_pattern: '"query_status": "file_not_found"'
      headers:
        Content-Type: application/x-www-form-urlencoded
      method: POST
      replace_pattern: "{SHA256}"
      url: https://mb-api.abuse.ch/api/v1/
